apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-demo
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'