apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: simple-oauth
  namespace: argocd
  labels:
    example: oauth
spec:
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, argoadmins, role:admin
      g, argousers, role:readonly
    scopes: '[groups]'
  server:
    insecure: true
    route:
      enabled: true
      tls:
        termination: edge

